const NANOIDLENGTH=8;
const PLAYERWAITTIME=10000;
const GAMEEXPIRYTIME=900;
const APPNAME="BoardFusion";
const APPURL="http://localhost:5173"
const VERIFICATIONTOKENEXPIRYTIME=600

export { NANOIDLENGTH, PLAYERWAITTIME ,GAMEEXPIRYTIME,APPNAME, APPURL, VERIFICATIONTOKENEXPIRYTIME
};
