const NANOIDLENGTH=8;
const PLAYERWAITTIME=10000;
const GAMEEXPIRYTIME=900;
const APPNAME="Othello";
const APPURL="http://localhost:5173"
export { NANOIDLENGTH, PLAYERWAITTIME ,GAMEEXPIRYTIME,APPNAME, APPURL};
