const NANOIDLENGTH=8;
const PLAYERWAITTIME=10000;
const GAMEEXPIRYTIME=900;
const APPNAME="BoardFusion";
const APPURL="http://localhost:5173"
const VERIFICATIONTOKENEXPIRYTIME=600
const OAUTH_REDIRECTURL=process.env.OAUTH_REDIRECT_URL
export { NANOIDLENGTH, PLAYERWAITTIME ,GAMEEXPIRYTIME,APPNAME, APPURL, VERIFICATIONTOKENEXPIRYTIME,
    OAUTH_REDIRECTURL 
};
